runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: theopencorps.app

